serverName: SleepingServer, waiting for his prince...
serverPort: 25565
maxPlayers: 3
loginMessage: ...Waking server up, come back in a minute...
serverOnlineMode: true
webPort: 0
webStopOnStart: false
startMinecraft: true
minecraftCommand: start-server.bat
version: false
